config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :photos, path: "gallery", only: [:index, :show]

  scope controller: :home do
    get 'index' => :index
    get 'about' => :about
    get 'contact' => :contact
    post '/contact/email' => :contact_email
  end
  

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: '/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
  self.inheritance_column = nil
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_attached_file :image,
    :styles => {
      :medium => {
        :geometry => '1000x1000',
        :quality => 90
      }
    }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :body
  validates_length_of :title, minimum: 8
  validates_uniqueness_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  def index
    @photos = Photo.all
  end

  def about
  end

  def contact
  end

  def contact_email
    if validate_captcha(params["g-recaptcha-response"])
      ContactMailer.contact_email(params).deliver
      flash[:notice] = "You email has been successfully sent."
      redirect_to action: "contact"
    else
      flash[:notice] = "Something went wrong. Please try again."
      render "contact"
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  require "uri"
  require "net/http"

  def validate_captcha(response)
    res = Net::HTTP.post_form(
    URI.parse('https://www.google.com/recaptcha/api/siteverify'),
      {
        'secret' => ENV["WOODGRAIN_CAPTCHA_SECRET"],
        'remoteip'   => request.ip,
        'response'   => response
      }
    )
    body = JSON.parse(res.body)

    body["success"]
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.slim
section#about
  h2 About
  div.bio-container
    div.headshot
      = image_tag('kathy.jpg', alt: "Kathleen Lachance")
    div.bio
      p As an art student in Detroit, I worked as a decorative artist on several Restoration Projects. It was then that I fell in love with the preservation and execution of faux finishes. The discipline of the decorative arts, in a historically correct manner, has been both challenging and rewarding. Knowing that I am one of the artists that has kept these art finishes alive has given me a great sense of joy and purpose.
      p In an age where craftsmanship is often sacrificed for the sake of expediency,  Woodgrain Studios is a company that places the craft before commerce.
      p Educating the public by preserving these Historical Landmarks truly tells the story of the artisans and craftsmen that have came before us.

= render partial: "shared/contact-cta", locals: {custom_text: "Kathleen is currently available for appraisals."}

app/views/home/contact.html.slim
- content_for :head do 
  <script src="https://www.google.com/recaptcha/api.js" async defer></script>

section#contact
  h2 Contact
  = form_tag('/contact/email')
    .input_field
      = label_tag 'name','Name'
      = text_field_tag :name, nil, required: true, minlength: 3, maxlength: 30
    .input_field
      = label_tag 'email','Email'
      = email_field_tag :email, nil, required: true, minlength: 3, maxlength: 50
    .input_field
      =label_tag 'phone', 'Phone number'
      = telephone_field_tag :phone, nil, required: false, minlength: 3, maxlength: 30
    .input_field
      = label_tag 'body', 'Message'
      = text_area_tag :body, nil, required: true, minlength: 3
    .input_field
      div.g-recaptcha data-sitekey="6LeCrUAUAAAAADK2KdZjEoGtu1EKk3F0msDUUuKP" data-callback="enableSubmit"
    .input_field
      = submit_tag "Send", id: "contact-submit", disabled: true

javascript:
  function enableSubmit(){
    document.getElementById("contact-submit").disabled = false;
  }

app/views/home/index.html.slim
.hero
  .cta
    h2 Where art and woodgrain meet.
    ul
      li
        = link_to "Our Story", about_path
      li
        = link_to "The Gallery", photos_path

section#services
  h2 Services
  ul
    li
      = image_tag('distressing.jpg', alt: "distressing")
      p Distressing
    li
      = image_tag('glazing.jpg', alt: "glazing")
      p Glazing
    li
      = image_tag('marbling.jpg', alt: "marbling")
      p Marbling
    li
      = image_tag('graining.jpg', alt: "graining")
      p Wood Graining
    li
      = image_tag('stenciling.jpg', alt: "stenciling")
      p Stencils
    li
      = image_tag('strie.jpg', alt: "strie")
      p Strie

= render partial: "shared/contact-cta", locals: {custom_text: nil}

app/views/layouts/application.html.slim
doctype html
html
  head
    title Woodgrain Studios
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Montserrat|Roboto'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = content_for :head
    = csrf_meta_tags
    <meta name="description" content="Woodgrain Studios | Where art and woodgrain meet.">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  
  body
    .content
      = render '/shared/header'
      = render '/shared/flash'
      = yield
  
    = render '/shared/footer'

app/views/photos/_photo.html.slim
.photo
  = image_tag(photo.image.url(:medium), alt: photo.title, class: "myImg")
  .caption
    = photo.title

app/views/photos/index.html.slim
section#gallery
  h2 Gallery
  .photos
    = render(@photos) || "Gallery is empty"

div#imageModal.modal
  span.close &times;
  img#modalImg.modal-content
  div#caption

javascript:
  var modal = document.getElementById('imageModal');
  var modalImg = document.getElementById("modalImg");
  var captionText = document.getElementById("caption");

  $(".myImg").click(function(){
    modal.style.display = "block";
    modalImg.src = this.src;
    captionText.innerHTML = this.alt;
  });

  var close = document.getElementsByClassName("close")[0];

  close.onclick = function() { 
    modal.style.display = "none";
  }

app/views/photos/show.html.slim
h1 Photos#show
p Find me in app/views/photos/show.html.slim

app/views/posts/index.html.slim
- @posts.each do |p|
  | <p>#{p.body.html_safe}</p>

app/views/posts/show.html.slim
h1 Posts#show
p Find me in app/views/posts/show.html.slim

app/views/shared/_contact-cta.html.slim
.contact-cta
  .cta-container
    h3 
      = custom_text || "Need a quote or have a question?"
    = link_to "Contact Us", contact_path

app/views/shared/_flash.html.slim
- if flash[:notice]
  p.flash.notice #{flash[:notice]}
- elsif flash[:alert]
  p.flash.alert #{flash[:alert]}

app/views/shared/_footer.html.slim
footer
  .copyright
    p &copy; Woodgrain Studios 2018
    p Designed and Developed by #{link_to 'Sam Lachance', 'https://samlachance.com'}
  = render partial: 'shared/nav'

  

app/views/shared/_header.html.slim
header
  h1 Woodgrain Studios
  = render partial: 'shared/nav'

app/views/shared/_nav.html.slim
nav
  ul
    li
      = link_to 'Home', index_path
    li
      = link_to 'About', about_path
    li
      = link_to 'Gallery', photos_path
    li
      = link_to 'Contact', contact_path